### ISSUE TITLE
Multiroom

### ISSUE THREAD

**Issue by paku74** [mercs600/ha-adb_service#16]
Joł!
Na początku chciałem podziękować za dobrą robotę, u mnie działa przepięknie.
A teraz pytanko: **Czy jest możliwość sterowania kilkoma dekoderami?** Oczywiście każdym oddzielnie.
W _configuration. yaml_ podajemy IP dekodera, jest jakaś możliwość, żeby zapisać w HA kilka dekoderów (kilka IP)
I jak zrobić żeby HA wiedziało, którym w danej chwili dekoderem chcemy sterować?

Pozdrawiam.

**Comment by jszkiela72** [comment]
It is possible. @mercs600 Can you add changes to the repository?

Change __init__.py
```
import json
import requests

DOMAIN = 'adb_service'

ATTR_KEY = 'key'
DEFAULT_KEY = 'StandBy'

CONF_HOSTS = 'hosts'
DEFAULT_HOSTS = ['192.168.0.174']

def setup(hass, config):
    hosts = config[DOMAIN].get(CONF_HOSTS, DEFAULT_HOSTS)
    if not isinstance(hosts, list):
        hosts = [hosts]
    success = False

    for idx, host in enumerate(hosts, 1):
        try:
            statusResponse = requests.get(f'http://{host}:8080/system/version')
            statusResponse = statusResponse.json()
            attributes = {
                'internal_version': statusResponse.get('internal_version'),
                'external_version': statusResponse.get('external_version'),
                'manufacturer': statusResponse.get('manufacturer'),
                'model': statusResponse.get('model'),
                'friendly_name': statusResponse.get('friendly_name'),
                'release': statusResponse.get('release')
            }

            sensor_name = f'sensor.adb_{idx}'
            service_name = f'press_{idx}'

            def make_press(host, sensor_name, attributes):
                def press(call):
                    name = call.data.get(ATTR_KEY, DEFAULT_KEY)
                    address = f'http://{host}:8080/control/rcu'
                    try:
                        response = requests.post(address, data={'Keypress': 'Key' + str(name)})
                    except Exception:
                        pass
                    hass.states.set(sensor_name, name, attributes)
                return press

            hass.states.set(sensor_name, '', attributes)
            hass.services.register(DOMAIN, service_name, make_press(host, sensor_name, attributes))
            success = True
        except Exception as e:
            print(f"ADB Service: Error initializing host {host}: {str(e)}")
            continue

    return success
```

Change services.yaml

```
press_1:
  description: Send press key event to ADB tuner #1
  fields:
    key:
      description: Name of key to send (e.g. StandBy, Five, VolumeUp, etc.)
      example: Five

press_2:
  description: Send press key event to ADB tuner #2
  fields:
    key:
      description: Name of key to send (e.g. StandBy, Five, VolumeUp, etc.)
      example: Five

press_3:
  description: Send press key event to ADB tuner #3 (if configured)
  fields:
    key:
      description: Name of key to send (e.g. StandBy, Five, VolumeUp, etc.)
      example: Five

press_4:
  description: Send press key event to ADB tuner #4 (if configured)
  fields:
    key:
      description: Name of key to send (e.g. StandBy, Five, VolumeUp, etc.)
      example: Five
```

Change the entry in configuration.yaml

```
adb_service:
  hosts:
    - 192.168.XXX.XXX
    - 192.168.XXX.XXX
 ```
If you want you can change ui-lovelace.yaml (more buttons).

```
## Please notice that is not fully working ui-lovelace file. You should copy/paste this snippet to your ui-lovelace file. 
- cards:
  - cards:
      - color_type: icon
        icon: 'mdi:power-standby'
        tap_action:
          action: call-service
          service: adb_service.press
        type: 'custom:button-card'
      - color_type: icon
        icon: 'mdi:volume-plus'
        tap_action:
          action: call-service
          service: adb_service.press
          service_data:
            key: VolumeUp
        type: 'custom:button-card'
      - color_type: icon
        icon: 'mdi:volume-minus'
        tap_action:
          action: call-service
          service: adb_service.press
          service_data:
            key: VolumeDown
        type: 'custom:button-card'
    type: horizontal-stack
  - cards:
      - color_type: icon
        icon: 'mdi:information-variant'
        tap_action:
          action: call-service
          service: adb_service.press
          service_data:
              key: Info
        type: 'custom:button-card'
      - color_type: icon
        icon: 'mdi:arrow-up-bold-box'
        tap_action:
          action: call-service
          service: adb_service.press
          service_data:
            key: Up
        type: 'custom:button-card'
      - color_type: icon
        icon: 'mdi:plus-box-outline'
        tap_action:
          action: call-service
          service: adb_service.press
          service_data:
            key: ProgramUp
        type: 'custom:button-card'
    type: horizontal-stack
  - cards:
      - color_type: icon
        icon: 'mdi:arrow-left-bold-box'
        tap_action:
          action: call-service
          service: adb_service.press
          service_data:
            key: Left
        type: 'custom:button-card'
      - color_type: icon
        name: OK
        aspect_ratio: 2/1
        tap_action:
          action: call-service
          service: adb_service.press
          service_data:
            key: Ok
        type: 'custom:button-card'
      - color_type: icon
        icon: 'mdi:arrow-right-bold-box'
        tap_action:
          action: call-service
          service: adb_service.press
          service_data:
            key: Right
        type: 'custom:button-card'
    type: horizontal-stack
  - cards:
      - color_type: icon
        icon: 'mdi:keyboard-return'
        tap_action:
          action: call-service
          service: adb_service.press
          service_data:
            key: Back
        type: 'custom:button-card'
      - color_type: icon
        icon: 'mdi:arrow-down-bold-box'
        tap_action:
          action: call-service
          service: adb_service.press
          service_data:
            key: Down
        type: 'custom:button-card'
      - color_type: icon
        icon: 'mdi:minus-box-outline'
        tap_action:
          action: call-service
          service: adb_service.press
          service_data:
            key: ProgramDown
        type: 'custom:button-card'
    type: horizontal-stack
  - cards:
      - color_type: icon
        tap_action:
          action: call-service
          service: adb_service.press
          service_data:
            key: One
        icon: 'mdi:numeric-1-box-outline'
        type: 'custom:button-card'
      - color_type: icon
        tap_action:
          action: call-service
          service: adb_service.press
          service_data:
            key: Two
        icon: 'mdi:numeric-2-box-outline'
        type: 'custom:button-card'
      - color_type: icon
        tap_action:
          action: call-service
          service: adb_service.press
          service_data:
            key: Three
        icon: 'mdi:numeric-3-box-outline'
        type: 'custom:button-card'
    type: horizontal-stack
  - cards:
    - color_type: icon
      tap_action:
        action: call-service
        service: adb_service.press
        service_data:
          key: Four
      icon: 'mdi:numeric-4-box-outline'
      type: 'custom:button-card'
    - color_type: icon
      tap_action:
        action: call-service
        service: adb_service.press
        service_data:
          key: Five
      icon: 'mdi:numeric-5-box-outline'
      type: 'custom:button-card'
    - color_type: icon
      tap_action:
        action: call-service
        service: adb_service.press
        service_data:
          key: Six
      icon: 'mdi:numeric-6-box-outline'
      type: 'custom:button-card'
    type: horizontal-stack
  - cards:
    - color_type: icon
      tap_action:
        action: call-service
        service: adb_service.press
        service_data:
          key: Seven
      icon: 'mdi:numeric-7-box-outline'
      type: 'custom:button-card'
    - color_type: icon
      tap_action:
        action: call-service
        service: adb_service.press
        service_data:
          key: Eight
      icon: 'mdi:numeric-8-box-outline'
      type: 'custom:button-card'
    - color_type: icon
      tap_action:
        action: call-service
        service: adb_service.press
        service_data:
          key: Nine
      icon: 'mdi:numeric-9-box-outline'
      type: 'custom:button-card'
    type: horizontal-stack
  - cards:
    - type: "custom:button-card"
      color_type: blank-card
    - color_type: icon
      tap_action:
        action: call-service
        service: adb_service.press
        service_data:
          key: Zero
      icon: 'mdi:numeric-0-box-outline'
      type: 'custom:button-card'
    - type: "custom:button-card"
      color_type: blank-card
    type: horizontal-stack
type: vertical-stack

## You should remember about it:
resources:
  - type: module
    url: /customcards/github/custom-cards/button-card.js?track=true
```
